server:
  port: 7070
spring:
  application:
    name: "Cards-Service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://guest:guest1234@cluster0.z97cb4s.mongodb.net/cards?retryWrites=true&w=majority"
  rabbitmq:
    addresses: "amqps://jrasplef:uhxSmsC5cJwyMoCqXlxf9Q4VaxtXNqnI@jackal.rmq.cloudamqp.com/jrasplef"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
